### ISSUE TITLE
Uploading track with the "Private" visibility by default uploads it as "Public".

### ISSUE THREAD

**Issue by ykartsev** [skyderby/skyderby#114]
Steps to reproduce:

1. Open Upload dialog.
2. Select "Private" visibility manually.
3. Upload a track.
4. Open Upload dialog, observing "Private" visibility selected by default now.
5. Upload a track.

The track uploaded second will have "Public" visibility instead of "Private".

**Comment by skyksandr** [comment]
Thank you for reporting. Just rolled fix to production.
