### ISSUE TITLE
Вычитание ветра. Вручную введенные данные о погоде.

### ISSUE THREAD

**Issue by skyksandr** [skyderby/skyderby#17]
**Соревнования**
- [x] Организатор должен иметь возможность ввести данные о погоде в соревновании.
- [x] Любой пользователь должен иметь возможность просмотреть данные о погоде в соревновании
- [x] Организатор должен иметь возможность включить вычитание ветра для соревнования. При выключенном вычитании ветра данные о погоде отображаются справочно.
- [x] Любой пользователь при включенном вычитании ветра должен иметь возможность просмотра результатов как с влиянием ветра, так и без.
- [ ] При загрузке трека при включенном вычитании ветра проверять, что ветер задан для текущего дня, при отсутствии данных о погоде выдавать ошибку.
- [ ] **??** При изменении данных о погоде пересчитывать результаты рассчитанных треков у которых дата записи больше чем новые сведения о погоде.
- [ ] При просмотре трека на странице соревнования должна быть возможность просмотра карты
- [ ] Карта должна отображать как реальную траекторию, так и скорректированную.
- [ ] Карта должна отображать Polar chart с данными о ветре.

**Треки**
- [ ] Владелец трека (только зарегистрированный пользователь) должен иметь возможность указать сведения о погоде.
- [x] Любой пользователь должен иметь возможность просмотра сведений о погоде.
- [x] Карта должна отображать как реальную траекторию, так и скорректированную.
- [x] Карта должна отображать Polar chart с данными о ветре.
- [ ] На странице карты должна быть возможность выбрать в каких единицах отображать скорость ветра;
- [ ] На странице карты должна быть возможность выбрать в каких единицах отображать скорости;
- [x] На странице карты должна быть возможность скрыть скорректированную траекторию.
- [x] Карта должна подстраиваться и вмещать обе траектории
- [x] Страница должна отображать индикаторы загрузки: индикатор загрузки скрипта google maps и индикатор загрузки данных трека

**Форма ввода данных о погоде**
- [x] Должна быть возможность ввести следующие сведения: Дата и время, начиная с которых действует запись; Высота, для которой актуальны данные; Скорость ветра; Направление ветра (ОТКУДА).
- [x] Должна быть возможность ввода высоты в метрах и в футах
- [x] Должна быть возможность ввода скорости ветра в м/с, км/ч, узлах, милях/час
- [x] Должна быть возможно просмотра данных о высоте в метрах и в футах
- [x] Должна быть возможность просмотра скорости ветра в м/с, км/ч, узлах, милях/час
- [x] В форму ввода данных о погоде должна автоматически подставляться дата и время для трека - начало часа на момент начала записи. 
- [x] Проверка заполнения. Дата и время должны быть заполнены.
- [x] Проверка заполнения. Высота должна быть заполнена, должна быть числовым значением и быть больше, либо равна нулю.
- [x] Проверка заполнения. Скорость ветра должна быть заполнена, должна быть числовым значением и быть больше, либо равна нулю.
- [x] Проверка заполнения. Направление ветра должно быть заполнено, должно быть числовым значением и быть больше 0 и меньше чем 360.
- [ ] В форму ввода данных о погоде должна автоматически подставляться дата и время для соревнования - на 8:00 текущего дня.
- [ ] Должна быть возможность редактирования введенных данных на определенной высоте вместо удаления и создания новой строки
- [x] Ошибка: После сохранения записи сбрасываются единицы измерения
- [ ] Группировка записей по дате/времени при вводе из соревнования
- [x] Скрыть дату/время для формы в треке

**Локализацая**
- [x] Русская локализация
- [ ] Немецкая локализация
- [ ] Французская локализация
- [ ] Испанская локализация

**Comment by alexgalda** [comment]
Форма ввода данных о погоде:
*) Добавить автоматическое вычисление оценочной скорости ветра в заданном диапазоне высот (не только 2000 - 3000) используя GPS данные со взлета и до полного наборы высоты согласно алгоритму Майкла Купера.

**Comment by alexgalda** [comment]
Форма ввода данных о погоде:
*) кнопка "Ok" выводящая обратно в основное окно и автоматически обновляющая результаты/карту
*) автоматический пересчет данных в таблице погодных данных при изменении единиц измерения (с корректным округлением но без накопления ошибки при многократном переключении)
*) сообщение об ошибке выводится на 1 секунду, а не висит пока не закроешь
*) возможность редактирования введенных данных на определенной высоте вместо необходимости удаления и создания новой строки
*) корректная интерпретация отрицательной скорости ветра с соответствующий изменением направления (-10m/s from NE = 10m/s from SW) или запрет ввода отрицательных значений
*) корректная интерпретация высоты с различным количеством цифр в записи (например, 11000м) и ее положения в таблице погодных данных
*) отображение интерполированного профиля ветра в координатах "скорость/направление" - "высота", который используется при рассчете результатов
**) кнопка автоматической подгрузки текущих данных (raw data) с http://glidelinesystems.com/winds во всем диапазоне высот до ~18,000ft

**Comment by skyksandr** [comment]
http://glidelinesystems.com/winds, кстати, используют Forecast model: NOAA GFS, я планировал сделать автоматическую загрузку данных и хранение для тех аэродромов для которых стоит признак.

**Comment by skyksandr** [comment]
@alexgalda, подскажи, как воспроизвести:

>  *) сообщение об ошибке выводится на 1 секунду, а не висит пока не закроешь

**Comment by alexgalda** [comment]
Ошибкой у тебя является ввод угла 360, например.

**Comment by skyksandr** [comment]
Верно, потому что 360 = 0.

**Comment by alexgalda** [comment]
Я понимаю, мне показалось что ты в последнем email спрашивал как
воспроизвести ошибку, вот я и написал)

**Comment by skyksandr** [comment]
@alexgalda можешь подробнее описать, что имеешь ввиду:
> отображение интерполированного профиля ветра в координатах "скорость/направление" - "высота", который используется при рассчете результатов

**Comment by alexgalda** [comment]
Дело в том, что несколько точек на полярной диаграмме - это слишком упрощенный подход к диаграмме силы и направления ветра.
Пока это не столь важно, но в идеале можно будет строить график подобного типа: 
![wind profile](https://cloud.githubusercontent.com/assets/18057530/14291603/e039b0ec-fb29-11e5-990d-76b1848ffb84.jpg)
Он более детально визуализирует информацию и дает возможность наглядно оценить точность вычисления ветра (если добавить error bars при использовании алгоритма Майкла).

**Comment by skyksandr** [comment]
Закрываю. Далее планирую выполнять доработки в рамках более мелких задач.
