### ISSUE TITLE
Setup video and track synchronization

### ISSUE THREAD

**Issue by skyksandr** [skyderby/skyderby#47]
**Problem** 

Setup video and track synchronization is available only through application console.

**Requirements**

Registered user should be able setup sync for his own tracks.

"Draft":
![2016-09-26 14 14 12](https://cloud.githubusercontent.com/assets/5262979/18834021/4dc986f4-83fc-11e6-97f5-1c54ba46cabf.png)

**Comment by skyksandr** [comment]
Note for me: Add validation that one track has only one video. At least for now, while multiple videos not planned and not requested by anyone.

**Comment by skyksandr** [comment]
@FloKas, @daniduarte could you please cook pull request with translation of the following locale files:
-  config/locales/models/track_videos.en.yml
-  config/locales/views/track_videos/edit.en.yml
-  config/locales/views/track_videos/form.en.yml
-  config/locales/views/track_videos/new.en.yml

**Comment by skyksandr** [comment]
Thank you @FloKas. I've updated app so it is online.

**Comment by daniduarte** [comment]
@skyksandr did you push the original files to get a example of them?
- config/locales/models/track_videos.en.yml
- config/locales/views/track_videos/edit.en.yml
- config/locales/views/track_videos/form.en.yml
- config/locales/views/track_videos/new.en.yml

**Comment by skyksandr** [comment]
@daniduarte Yes, I did. Have you done `git fetch upstream` or `git pull upstream dev`?

**Comment by daniduarte** [comment]
All done! But I can't find config/locales/views/track_videos/new.en.yml file, could you please create it and tell me to translate to spanish?

**Comment by daniduarte** [comment]
I pushed my commits with the ready translations

**Comment by skyksandr** [comment]
All work on this issue is done.
