### ISSUE TITLE
Display mountain profile

### ISSUE THREAD

**Issue by skyksandr** [skyderby/skyderby#49]
**Requirements**

User should be able to see exit profile/mountain profile.

Mountain profile should be defined for `Place` as two dimensional. In example:

| Abs. Altitude (above sea level) | Distance from exit |
| --- | --- |
| 1200 | 0 |
| 1150 | 10 |
| 1050 | 20 |

Requested by: Simon Perriard

**Comment by simonperriard** [comment]
to think about : the most interesting thing is to compare a measured profile of a mountain with a track record, but not necessarily at the same place. For exemple if I want to jump a new place, it would be cool to be able to compare the new place profile with many of my existing trajectories so I can figure out what kind of margin I would have on the new jump. A drop down list on the track graph page would be nice for this purpose.

**Comment by skyksandr** [comment]
Implemented. Already on production.
